# Generated by Django 3.1.1 on 2020-09-12 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_mediatype_parent_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediatype',
            name='file_extension',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
