# Generated by Django 3.1.1 on 2020-09-13 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_mediatype_file_extension'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediatype',
            name='type_code',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
