# Generated by Django 3.1.1 on 2020-09-13 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_auto_20200913_0301'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediatype',
            name='pattern',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='mediatype',
            name='parent_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_types', to='assets.mediatype'),
        ),
    ]
